import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ShieldAlert } from "lucide-react";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Risk Disclosure | AI Gold Forecast",
  description: "Full risk disclosure and disclaimer for AI Gold Forecast. Trading precious metals involves substantial risk of loss.",
};

export default function RiskDisclosurePage() {
  return (
    <div className="min-h-screen text-white" style={{ backgroundColor: "#06070a" }}>
      {/* Ambient glows */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-[rgba(212,175,55,0.04)] rounded-full blur-[120px] pointer-events-none" />

      <div className="w-full px-4 md:px-12 py-8 relative z-10">
        {/* Navigation */}
        <header className="flex items-center justify-between mb-12 border-b border-outline-variant/30 pb-6">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-on-surface-variant hover:text-white transition-colors duration-200 group no-underline"
          >
            <ArrowLeft className="h-4 w-4 transition-transform duration-200 group-hover:-translate-x-1" />
            Back to Terminal
          </Link>
          <div className="flex items-center gap-2 text-xs text-on-surface-variant bg-primary/5 px-3 py-1 rounded-full border border-primary/20">
            <ShieldAlert className="h-3.5 w-3.5 text-primary" />
            Legal Disclosure
          </div>
        </header>

        <article className="rounded-xl glass-card p-6 sm:p-10">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-primary/20 bg-primary/5 text-primary text-xs font-semibold uppercase tracking-wider mb-6">
            <ShieldAlert className="h-3 w-3" />
            Important Notice
          </div>

          <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-white mb-8 leading-tight font-playfair">
            Risk Disclosure &amp; <span className="gold-shimmer-text">Disclaimer</span>
          </h1>

          <div className="prose prose-invert max-w-none space-y-6 text-on-surface-variant text-base leading-relaxed">
            <div className="border border-primary/20 bg-primary/5 rounded-xl p-5 mb-8">
              <p className="text-primary font-semibold text-sm">
                Please read this risk disclosure statement carefully before using AI Gold Forecast or acting on any information provided by this platform. Your use of our website, tools, forecasts, and any associated content constitutes your agreement to the terms outlined below.
              </p>
            </div>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">1. General Disclaimer</h2>
            <p>
              AI Gold Forecast (&ldquo;the Platform&rdquo;) is an educational and informational resource that provides AI-generated market forecasts, technical analysis, trading strategies, and financial commentary related to gold (XAU/USD) and other precious metals. All content, signals, predictions, and analyses published on this platform are generated by machine learning models and automated systems. They are intended strictly for educational and informational purposes and should not be interpreted as personalized financial advice, investment recommendations, or solicitations to buy, sell, or hold any financial instrument.
            </p>
            <p>
              The creators, operators, and contributors of AI Gold Forecast are not licensed financial advisors, portfolio managers, or investment professionals. No fiduciary relationship exists between this platform and its users. We strongly recommend consulting a qualified, licensed financial advisor before making any trading or investment decisions.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">2. Trading Risk Warning</h2>
            <p>
              Trading gold, foreign exchange (forex), contracts for difference (CFDs), and other financial instruments carries a high level of risk and may not be suitable for all investors. You could sustain a loss of some or all of your initial investment. Do not invest money that you cannot afford to lose. The high degree of leverage available in these markets can work both for and against you. Before deciding to trade, you should carefully consider your investment objectives, level of experience, risk appetite, and financial situation.
            </p>
            <p>
              The value of gold and other precious metals is subject to significant fluctuations driven by global economic conditions, geopolitical events, central bank policies, currency movements, inflation expectations, supply and demand dynamics, and market sentiment. These factors are inherently unpredictable, and no forecasting model — regardless of its sophistication — can guarantee accuracy in predicting future price movements.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">3. No Guarantee of Accuracy</h2>
            <p>
              While AI Gold Forecast employs advanced deep learning neural networks, quantitative models, and technical indicators to generate market forecasts, we make no warranty, representation, or guarantee regarding the accuracy, completeness, timeliness, or reliability of any forecast, signal, analysis, or content published on this platform. Past performance of our AI models does not guarantee future results. Historical accuracy rates are provided for transparency and educational purposes only and should not be relied upon as indicators of future performance.
            </p>
            <p>
              Machine learning models are trained on historical data and may fail to anticipate unprecedented market events, flash crashes, black swan scenarios, geopolitical shocks, regulatory changes, or other extraordinary circumstances. Users should always exercise independent judgment and perform their own due diligence before acting on any information provided by this platform.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, AI Gold Forecast, its owners, operators, affiliates, employees, agents, and contributors shall not be held liable for any direct, indirect, incidental, consequential, special, or exemplary damages — including but not limited to loss of profits, loss of data, loss of capital, trading losses, or business interruption — arising from or in connection with your use of, or inability to use, this platform and its content.
            </p>
            <p>
              You acknowledge and agree that your use of AI Gold Forecast is entirely at your own risk. Any actions taken based on the forecasts, signals, strategies, or analyses provided by this platform are your sole responsibility. We disclaim all liability for any financial losses or damages resulting from your reliance on the information presented herein.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">5. Third-Party Links &amp; Affiliations</h2>
            <p>
              This platform may contain links to third-party websites, brokerage services, and financial products. These links are provided for informational and referral purposes. AI Gold Forecast may receive affiliate commissions from brokers or service providers when users register or trade through our referral links. This affiliate relationship does not influence the objectivity of our forecasts or analyses. However, you should be aware of this relationship and conduct your own research before opening an account with any third-party broker or service provider.
            </p>
            <p>
              We do not endorse, guarantee, or assume responsibility for the accuracy, legality, or content of any third-party website or service. Your interactions with third-party services are governed by their respective terms of service and privacy policies.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">6. Regulatory Compliance</h2>
            <p>
              AI Gold Forecast does not provide services in jurisdictions where such services would be contrary to local laws or regulations. It is your responsibility to determine whether the use of this platform is legal in your jurisdiction. The availability of this website does not constitute an offer or solicitation in any jurisdiction where such activity is prohibited or restricted.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">7. Data Privacy &amp; Security</h2>
            <p>
              We are committed to protecting the privacy and security of our users. Any personal data collected through this platform is processed in accordance with applicable data protection regulations. We do not sell, rent, or share your personal information with third parties for marketing purposes. For more information, please review our privacy practices.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">8. Intellectual Property</h2>
            <p>
              All content, forecasts, analyses, strategies, software, algorithms, and visual designs published on AI Gold Forecast are protected by intellectual property laws. Unauthorized reproduction, distribution, modification, or commercial use of our content without prior written permission is strictly prohibited.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">9. Modifications to This Disclosure</h2>
            <p>
              AI Gold Forecast reserves the right to modify, update, or amend this risk disclosure statement at any time without prior notice. Your continued use of the platform after any such changes constitutes your acceptance of the revised terms. We encourage you to review this page periodically for updates.
            </p>

            <h2 className="text-2xl font-bold text-white font-playfair border-l-4 border-primary pl-3 !mt-8 !mb-4">10. Final Acknowledgment</h2>
            <div className="border border-[#ef5350]/20 bg-[#ef5350]/5 rounded-xl p-5">
              <p className="text-on-surface font-semibold text-sm">
                By accessing and using AI Gold Forecast, you confirm that you have read, understood, and agreed to this risk disclosure in its entirety. You acknowledge that trading in financial markets carries inherent risks, that no forecasting system is infallible, and that you are solely responsible for your own trading decisions and their financial consequences. If you do not agree with any part of this disclosure, you should immediately cease using this platform.
              </p>
            </div>

            <p className="text-on-surface-variant/50 text-xs !mt-8 text-center">
              Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })} · AI Gold Forecast · All Rights Reserved
            </p>
          </div>
        </article>
      </div>
      <Footer />
    </div>
  );
}
